exclude: '^(tests/test_elements\.py|documents/knowledge/[eE]lements\.(md|txt)|static/parsed_yaml\.js)$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: regen-test-elements-py
        name: Regenerate tests/test_elements.py
        entry: python documents/knowledge/processor.py
        language: python
        additional_dependencies: [pyyaml]
        files: documents/knowledge/elements.yaml
        pass_filenames: false

      - id: yaml-to-txt
        name: Generate documents/knowledge/elements.txt
        entry: python documents/knowledge/yaml_to_txt.py
        language: python
        additional_dependencies: [pyyaml]
        files: documents/knowledge/elements.yaml
        pass_filenames: false

      - id: yaml-to-md
        name: Generate documents/knowledge/elements.md
        entry: python documents/knowledge/yaml_to_md.py
        language: python
        additional_dependencies: [pyyaml]
        files: documents/knowledge/elements.yaml
        pass_filenames: false

      - id: yaml-to-js
        name: Generate static/parsed_yaml.js
        entry: python documents/knowledge/yaml_to_js.py
        language: python
        additional_dependencies: [pyyaml]
        files: documents/knowledge/elements.yaml
        pass_filenames: false
        pass_filenames: false

      - id: sort-elements
        name: Sort elements in elements.py
        entry: python sort_element_functions.py
        language: python
        additional_dependencies: []
        files: vyxal/elements.py
        pass_filenames: false
