name: Lint, format, and update resources

on:
  push:
    paths-ignore:
      - "documentation/**"
      - "contributing/**"
      - "pages/**"

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - uses: coursier/cache-action@v6
      - name: Run Scalafix and Scalafmt
        run: sbt vyxalJVM/scalafix vyxalJVM/scalafmt
      - name: Stage changes
        run: git add .
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Scalafix changes"
  gen-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - uses: coursier/cache-action@v6
      - name: Update elements.txt and trigraphs.txt
        run: ./mill jvm.docs
      - name: Update nanorc files for JLine
        run: ./mill jvm.nanorc
      - name: Stage changes
        run: git add .
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Refresh element and/or trigraph docs from recent commit"
