name: Lint, format, and update resources

on:
  push:
    paths-ignore:
      - "documentation/**"
      - "contributing/**"
      - "pages/**"

env:
  JAVA_OPTS: ${{ vars.JAVA_OPTS }}

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: 17
          apps: scalafix
      - name: Run Scalafix
        run: scalafix --check --syntactic --scala-version=3.3.0 shared jvm js native
      - name: Run Scalafmt
        run: |
          ./mill mill.scalalib.scalafmt.ScalafmtModule/reformatAll __.sources
      - name: Stage changes
        run: git add .
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Scalafix changes"
  gen-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Update all documentation files
        run: ./mill jvm.docs
      - name: Update nanorc files for JLine
        run: ./mill jvm.nanorc
      - name: Stage changes
        run: git add .
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Refresh element and/or trigraph docs from recent commit"
